apiVersion: v1
data:
  config.json: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJoYWtvYm1rb3lhbjc3MSIsInBhc3N3b3JkIjoiZGNrcl9wYXRfNDN1b0Y1d3lLeWpxZDZXSVVlQm5VWG5YbXpjIiwiZW1haWwiOiJoYWtvYi5ta295YW43NzFAZ21haWwuY29tIiwiYXV0aCI6ImFHRnJiMkp0YTI5NVlXNDNOekU2WkdOcmNsOXdZWFJmTkROMWIwWTFkM2xMZVdweFpEWlhTVlZsUW01VldHNVliWHBqIn19fQ==
kind: Secret
metadata:
  name: docker-config
type: Opaque
