apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6IHsiaHR0cHM6Ly9pbmRleC5kb2NrZXIuaW8vdjEvIjogeyJhdXRoIjogImFHRnJiMkp0YTI5NVlXNDNOekU2U0cweE1qTTBLaW9xS2lRPSJ9fX0=
kind: Secret
metadata:
  name: docker-config
type: kubernetes.io/dockerconfigjson
