apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsiYXV0aCI6ImFHRnJiMkp0YTI5NVlXNDNOekU2U0cweE1qTTBLaW9xS2lRPSJ9fX0K
kind: Secret
metadata:
  name: docker-config
type: Opaque
