podTemplate(
    containers: [
        containerTemplate (
            name: "kaniko",
            image: "gcr.io/kaniko-project/executor:debug",
            command: "sleep",
            args: "99d"
        )],
    volumes: [
        secretVolume( 
            mountPath: '/kaniko/.docker/', 
            secretName: 'docker-config'
          )
        ]
      )
      {
        node (POD_LABEL) {
            stage("Get a Terraform project") {
                git url: "https://github.com/hashicorp/terraform.git", branch: "main"
                container("kaniko") {
                    stage("Build a Terraform project") {
                        sh '''
                            /kaniko/executor --dockerfile="./Dockerfile" --context=`pwd` --destination="hakobmkoyan771/terraform:0.1.0"
                        '''
                    }
                }
            }
        }
    }
